name: keypoint_moseq

channels:
  - conda-forge
  - nvidia
  - defaults

dependencies:
  - python=3.9
  - pytables
  - jaxlib=0.3.22=*cuda*
  - jax
  - cuda-nvcc
  - pip
  - pip:
    - "git+https://github.com/dattalab/jax-moseq.git@32c5286b5f11e260cb95840572beea736c3d1a0f#egg=jax-moseq"
    - "--editable=."
    - jupyterlab