name: keypoint_moseq

channels:
  - defaults
  - conda-forge
  - nvidia

dependencies:
  - python=3.9
  - pytables
  - cudatoolkit=11.2
  - cudnn=8.2
  - conda-forge::jax=0.3.22
  - conda-forge::jaxlib=0.3.22=*cuda*
  - cuda-nvcc
  - pip
  - pip:
    - "git+https://github.com/dattalab/jax-moseq.git@32c5286b5f11e260cb95840572beea736c3d1a0f#egg=jax-moseq"
    - "--editable=."
    - jupyterlab