name: keypoint_moseq

channels:
  - conda-forge
  - nvidia
  - defaults

dependencies:
  - python=3.9
  - pytables
  - jaxlib=0.3.22=*cuda*
  - jax
  - cuda-nvcc
  - pip
  - pip:
    - "jax-moseq==0.0.0"
    - "--editable=../"
    - jupyterlab
