name: keypoint_moseq

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytables
  - openblas
  - numpy=1.23.5
  - pip
  - pip:
    - jax==0.3.22
    - jaxlib==0.3.22
    - "jax-moseq"
    - "--editable=../"
    - jupyterlab